In [11]:
#1 
from array import*
import numpy as np
a = np.array([(1, 2), (3, 4), (5,6)])
print("Le tableau initial: ")
print(a)
a_list= a.tolist()
print("Le tableau initial convertit en liste avec les mêmes éléments: ")
print(a_list)


Le tableau initial: 
[[1 2]
 [3 4]
 [5 6]]
Le tableau initial convertit en liste avec les mêmes éléments: 
[[1, 2], [3, 4], [5, 6]]


In [1]:
#2
import numpy as np

n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])
  
print("Le tableau initial est: ")
print(n_array)
  
diag = np.diagonal(n_array)
  
print("Les éléments de la diagonale sont: ")
print(diag)
  
print("La somme des éléments de la diagonale: ")
print(sum(diag))

Le tableau initial est: 
[[55 25 15]
 [30 44  2]
 [11 45 77]]
Les éléments de la diagonale sont: 
[55 44 77]
La somme des éléments de la diagonale: 
176


In [37]:
#3
a = np.array([[1,2],[3,5]])
print("Le tableau initial est:")
print(a)
x=3
print("Les valeurs plus grandes que 3 sont: ", a[a>=x])


Le tableau initial est:
[[1 2]
 [3 5]]
Les valeurs plus grandes que 3 sont:  [3 5]


In [40]:
#4
A=np.array([[1,2,3],[4,5,6]])
print("La liste A est: ")
print(A)
B=np.array([[1,2,3],[4,5,6]])
print("La liste B est: ")
print(B)
C=A+B
print("La somme des deux listes est: ")
print(C)

La liste A est: 
[[1 2 3]
 [4 5 6]]
La liste B est: 
[[1 2 3]
 [4 5 6]]
La somme des deux listes est: 
[[ 2  4  6]
 [ 8 10 12]]


In [26]:
#5
import numpy as np
a= np.array([[1,88,3,4],[1,2,67,4]])
print("Le tableau initial est: ")
print(a)
l=[]
for i in a:
    s=i.mean()
    print("la moyenne= ")
    print(s)
    for n in i:
        x=n-s
        l.append(x)
print("les éléments - la moyenne= ")
print(l)
    


Le tableau initial est: 
[[ 1 88  3  4]
 [ 1  2 67  4]]
la moyenne= 
24.0
la moyenne= 
18.5
les éléments - la moyenne= 
[-23.0, 64.0, -21.0, -20.0, -17.5, -16.5, 48.5, -14.5]
